<a href="https://colab.research.google.com/github/aabarzu/Coding-Dojo/blob/main/EjerciciosTuberiasAbulon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [137]:
from google.colab import drive
drive.mount('/content/drive',  force_remount=True) #  force_remount=True , pide eso no sé porqué

Mounted at /content/drive


In [138]:
import pandas as pd
from pandas.core.frame import DataFrame

import matplotlib.pyplot as plt #from matplotlib import pyplot as plt
import plotly.express as px
from plotly.subplots import make_subplots
import seaborn as sns

import missingno as msno
import numpy as np

sns.set_theme()

In [139]:
# LIBRERIAS MACHINE LEARNING

from sklearn                 import metrics                # Metricas (Matriz de Confunsión)

from sklearn.linear_model    import LogisticRegression     # Regresión Logistica
from sklearn.linear_model    import LinearRegression       # Regresión Lineal

from sklearn.neighbors       import KNeighborsClassifier   # Knn como clasificador
from sklearn.neighbors       import KNeighborsRegressor    # Knn como Regresor

from sklearn.tree            import DecisionTreeClassifier # Arboles de Decisión Clasificador
from sklearn.tree            import DecisionTreeRegressor  # Arboles de Decisión Regresor

from sklearn.ensemble        import BaggingClassifier      # Bagging and pasting Classifier
from sklearn.ensemble        import BaggingRegressor       # Bagging and pasting Regressor 

from sklearn.ensemble        import RandomForestClassifier # Bosques aleatorios (Random Forests)
from sklearn.ensemble        import RandomForestRegressor  # Bosques aleatorios (Random Forests) Regres

from sklearn.model_selection import GridSearchCV           # Grid Search Cross Validation
from sklearn.model_selection import RandomizedSearchCV     # Para Pruebas Random

from sklearn.model_selection import train_test_split       # Para dividir las pruebas

from sklearn                 import tree                   # Grficar Arboles

# PARA OBTENER METRICAS

from sklearn.metrics         import mean_absolute_error    # Error absoluto medio (MAE)
from sklearn.metrics         import mean_squared_error     # Error cuadrático medio (MSE) y Raíz del error cuadrático medio (RMSE)
from sklearn.metrics         import r2_score               # Determinar el r2 score

#Transformacion de Datos scalar, normalizar y standarizacion OneHotencoding LabelEncoder 

from sklearn.preprocessing    import LabelEncoder          # Definir clasificación de una columna Texto Variables Categoricas
from sklearn.preprocessing    import StandardScaler        # Standarización de Datos
from sklearn.preprocessing    import OneHotEncoder         # OneHotEncoder 

from sklearn.linear_model     import Ridge
from sklearn.metrics          import roc_auc_score, plot_roc_curve ,accuracy_score

from sklearn.pipeline        import make_pipeline
from sklearn.pipeline        import Pipeline

In [140]:
def CargaDatos(filename):
  
  extension = filename[filename.find('.')+1:]
  path = "/content/drive/MyDrive/CodingDojo/DataScience/PandasForDataManipulation/Datos/"

  filename = path + filename
  if extension.lower() == 'csv':
      df = pd.read_csv(filename)   # csv
  
  if extension.lower() == 'xlsx':
      df = pd.read_excel(filename) # Excel

  return df

In [141]:
filename = 'abalone.csv'    

df = CargaDatos(filename)

In [142]:
def FuncValoresColumns(vpdf , vpfield):
  ValuesColumn = np.unique(vpdf[vpfield])
  
  return ValuesColumn , len(ValuesColumn)


def FuncLabelEncoderColumn(vpdf , vpfield):
  
  # creating instance of labelencoder
  labelencoder = LabelEncoder()

  vpdf[vpfield] = labelencoder.fit_transform(vpdf[vpfield])

  return vpdf

def FuncOneHotEncoderColumns(vpdf , vpfield):

  # creating instance of one-hot-encoder
  onehothncoder = OneHotEncoder(handle_unknown='ignore',categories='auto')

  # crea un dataframe con la nuevas columnas

  ValuesColumn , LenValuesColumn = FuncValoresColumns(vpdf , vpfield)

  ValuesColumn = [ vpfield + '_' + str(cls_label)  for cls_label in ValuesColumn ]

  enc_df = pd.DataFrame(onehothncoder.fit_transform( vpdf[[vpfield]]).toarray(), columns=ValuesColumn) 

  vpdf.drop(columns = vpfield , inplace = True)

  # Une los dos dataframe
  vpdf = vpdf.join(enc_df)
  
  return vpdf    

In [143]:
df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [144]:
df.isna().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weight    0
Viscera weight    0
Shell weight      0
Rings             0
dtype: int64

In [145]:
df_valores = df.copy()

In [146]:
FuncValoresColumns(df_valores, 'Sex')

(array(['F', 'I', 'M'], dtype=object), 3)

In [147]:
df_valores = FuncLabelEncoderColumn(df_valores, 'Sex')
df_valores

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0       2   0.455     0.365   0.095        0.5140          0.2245   
1       2   0.350     0.265   0.090        0.2255          0.0995   
2       0   0.530     0.420   0.135        0.6770          0.2565   
3       2   0.440     0.365   0.125        0.5160          0.2155   
4       1   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    0   0.565     0.450   0.165        0.8870          0.3700   
4173    2   0.590     0.440   0.135        0.9660          0.4390   
4174    2   0.600     0.475   0.205        1.1760          0.5255   
4175    0   0.625     0.485   0.150        1.0945          0.5310   
4176    2   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [149]:
X = df_valores.drop(columns=['Rings']).values 


In [150]:
X

array([[0.2   , 0.455 , 0.365 , ..., 0.2245, 0.101 , 0.15  ],
       [0.2   , 0.35  , 0.265 , ..., 0.0995, 0.0485, 0.07  ],
       [0.    , 0.53  , 0.42  , ..., 0.2565, 0.1415, 0.21  ],
       ...,
       [0.2   , 0.6   , 0.475 , ..., 0.5255, 0.2875, 0.308 ],
       [0.    , 0.625 , 0.485 , ..., 0.531 , 0.261 , 0.296 ],
       [0.2   , 0.71  , 0.555 , ..., 0.9455, 0.3765, 0.495 ]])

In [151]:
y = df_valores['Rings'].values # para arboles
y

array([15,  7,  9, ...,  9, 10, 12])

# **KNeighbors Regressor**

In [164]:
score = list()

for n_neighbors in range(1, 30 , 1):
  
  X_train, X_test , y_train , y_test = train_test_split(X,y,test_size=0.3, random_state = 42) # Datos para usar

  pipe = make_pipeline(StandardScaler(), # Escalamiento
                       KNeighborsRegressor(n_neighbors=n_neighbors) # Clasificación
                    )
  pipe.fit(X_train, y_train) 
  
  
  score.append( pipe.score(X_test, y_test) * 100)

  
  
print(score)



[11.361991617842548, 36.07375319102887, 42.48559616765083, 48.91161836359304, 50.294864469416844, 51.025849035161784, 50.81936220611553, 51.450257610373704, 52.08393389021592, 52.1152144599355, 51.83339568830885, 52.04511676245285, 52.309201979385, 52.124820892154666, 52.392621069553805, 52.36177008776315, 52.171839430815446, 52.29836731470541, 52.28098156482521, 52.26785920946399, 51.94240979877056, 52.077134034610275, 52.08413219264501, 52.213999444875995, 52.04131987291745, 51.902699186295244, 52.034337593349456, 52.04367546818127, 52.00252528233877]


In [165]:
pd.DataFrame( score ).max()

0    52.392621
dtype: float64

# **KNeighbors Clasificador**

In [170]:
df_valores = df

In [171]:
df_valores = FuncLabelEncoderColumn(df_valores, 'Sex')
df_valores

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0       2   0.455     0.365   0.095        0.5140          0.2245   
1       2   0.350     0.265   0.090        0.2255          0.0995   
2       0   0.530     0.420   0.135        0.6770          0.2565   
3       2   0.440     0.365   0.125        0.5160          0.2155   
4       1   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    0   0.565     0.450   0.165        0.8870          0.3700   
4173    2   0.590     0.440   0.135        0.9660          0.4390   
4174    2   0.600     0.475   0.205        1.1760          0.5255   
4175    0   0.625     0.485   0.150        1.0945          0.5310   
4176    2   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [172]:
X = df_valores.drop(columns=['Sex']).values 
X

array([[ 0.455 ,  0.365 ,  0.095 , ...,  0.101 ,  0.15  , 15.    ],
       [ 0.35  ,  0.265 ,  0.09  , ...,  0.0485,  0.07  ,  7.    ],
       [ 0.53  ,  0.42  ,  0.135 , ...,  0.1415,  0.21  ,  9.    ],
       ...,
       [ 0.6   ,  0.475 ,  0.205 , ...,  0.2875,  0.308 ,  9.    ],
       [ 0.625 ,  0.485 ,  0.15  , ...,  0.261 ,  0.296 , 10.    ],
       [ 0.71  ,  0.555 ,  0.195 , ...,  0.3765,  0.495 , 12.    ]])

In [173]:
y = df_valores['Sex'].values # para arboles
y

array([2, 2, 0, ..., 2, 0, 2])

In [175]:
score = list()

for n_neighbors in range(1, 30 , 1):
  
  X_train, X_test , y_train , y_test = train_test_split(X,y,test_size=0.3, random_state = 42) # Datos para usar

  pipe = make_pipeline(StandardScaler(), # Escalamiento
                       KNeighborsClassifier(n_neighbors=n_neighbors) # Clasificación
                    )
  pipe.fit(X_train, y_train) 
  
  score.append( pipe.score(X_test, y_test) * 100)

  
  
print(score)



[49.52153110047847, 49.52153110047847, 51.27591706539075, 52.07336523125997, 53.2695374800638, 53.03030303030303, 53.50877192982456, 52.71132376395534, 54.066985645933016, 53.588516746411486, 54.30622009569378, 53.827751196172244, 53.66826156299841, 52.95055821371611, 53.03030303030303, 52.23285486443381, 52.95055821371611, 53.588516746411486, 53.98724082934609, 53.66826156299841, 54.385964912280706, 54.385964912280706, 55.183413078149925, 55.02392344497608, 54.78468899521531, 55.26315789473685, 55.58213716108453, 55.74162679425837, 55.90111642743222]


In [176]:
pd.DataFrame( score ).max()

0    55.901116
dtype: float64

Después de que hayas completado las dos tareas, responde las siguientes preguntas. 

¿Por qué querrías ocupar una tubería para KNN?

   **Reduce los pasos a ejecutar**

¿Para qué otros modelos o tareas sería útil usar una tubería?

**Para cuando se necesita varios pasos , como escalar, PCA, y usar un modelo**
