<a href="https://colab.research.google.com/github/aabarzu/Coding-Dojo/blob/main/MetricasRegresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [175]:
# Error absoluto medio (MAE)
def CalculoMAE(y_test , y_pred):
    
    return   ( abs(y_test - y_pred)).sum() / len(y_test)

   

In [195]:
# Error cuadrático medio (MSE)
def CalculoMSE(y_test , y_pred):
  
  if y_test.size == y_pred.size:
    return ((y_test - y_pred) ** 2.0).sum()/len(y_test) 
    # (  (y_test - y_pred) ** 2.0 ).sum /len(y_test) 

  if y_test.size != y_pred.size:  
    return 0.0


In [207]:
# Raíz del error cuadrático medio (MSE):
import math
def CalculoRaizMSE(y_test , y_pred):
  return math.sqrt(CalculoMSE(y_test , y_pred)) 
  

In [146]:
# Determinación de coeficiente
def CalculoR2( y_test , y_pred):
  
  pass

In [147]:


y_test =  np.arange(0,10,0.75)
y_pred =  ( 0.75*np.random.rand(len(y_test)) - 2 ) + y_test 


In [148]:
y_test.reshape(-1,1)

array([[0.  ],
       [0.75],
       [1.5 ],
       [2.25],
       [3.  ],
       [3.75],
       [4.5 ],
       [5.25],
       [6.  ],
       [6.75],
       [7.5 ],
       [8.25],
       [9.  ],
       [9.75]])

In [149]:
y_pred.reshape(-1,1)

array([[-1.62187858],
       [-0.50015035],
       [ 0.17334686],
       [ 0.31079605],
       [ 1.39502358],
       [ 1.93552299],
       [ 2.8168334 ],
       [ 3.93860462],
       [ 4.47848858],
       [ 4.79143662],
       [ 5.61382346],
       [ 6.35048104],
       [ 7.60959153],
       [ 8.31599168]])

In [150]:
CalculoMAE( y_test, y_pred ) , CalculoMSE( y_test, y_pred) , round( CalculoRaizMSE(y_test , y_pred) , 5 )

(array([0.11584847, 0.08929645, 0.09476094, 0.13851457, 0.11464117,
        0.1296055 , 0.12022619, 0.0936711 , 0.10867939, 0.13989738,
        0.1347269 , 0.13567993, 0.09931489, 0.10242917]), 36.61887, 6.05135)

In [213]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import r2_score
import numpy as np


Y_test =   [1,1,2,2,4]  
  
Y_pred =   [0.6,1.29,1.99,2.69,3.4]  

Y_test_np =  np.array( Y_test  )
  
Y_pred_np =  np.array( Y_pred )

mae = mean_absolute_error(Y_test, Y_pred)
mse  = mean_squared_error(Y_test, Y_pred)
rmse = mean_squared_error(Y_test, Y_pred, squared=False)
r2   = r2_score(Y_test, Y_pred)

print(f"Con Librerias mae = {mae}, mse = {mse}, rmse = {rmse}, R2 ={r2}")
print(f"Calculadas    MAE = {CalculoMAE( Y_test_np , Y_pred_np )}, MSE = {CalculoMSE(Y_test_np , Y_pred_np)}, SMSE = {CalculoRaizMSE( Y_test_np , Y_pred_np)}"  )

Con Librerias mae = 0.398, mse = 0.21606, rmse = 0.4648225467853297, R2 =0.81995
Calculadas    MAE = 0.398, MSE = 0.21606, SMSE = 0.4648225467853297


Liberias from sklearn.metrics import mean_squared_error